(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(ecb-analyse-face (quote font-lock-warning-face))
 '(ecb-analyse-general-face (quote ecb-analyse-general-face))
 '(ecb-auto-activate t)
 '(ecb-directories-general-face (quote ecb-default-general-face))
 '(ecb-directory-face (quote font-lock-warning-face))
 '(ecb-eshell-auto-activate nil)
 '(ecb-history-bucket-node-dir-soure-path-face (quote ecb-history-bucket-node-face))
 '(ecb-history-face (quote font-lock-warning-face))
 '(ecb-history-general-face (quote ecb-default-general-face))
 '(ecb-layout-name "rightc4")
 '(ecb-method-face (quote font-lock-warning-face))
 '(ecb-methods-general-face (quote ecb-default-general-face))
 '(ecb-options-version "2.40")
 '(ecb-primary-secondary-mouse-buttons (quote mouse-1--mouse-2))
 '(ecb-source-face (quote font-lock-warning-face))
 '(ecb-source-path (quote (("~/ps/swiftlet/src/test/scala/com/twitter/swiftlet" "swift_test") ("~/ps/swiftlet/src/main/scala/com/twitter/swiftlet" "swift") ("/" "/"))))
 '(ecb-sources-general-face (quote ecb-default-general-face))
 '(ecb-tag-header-face (quote font-lock-warning-face))
 '(ecb-use-speedbar-instead-native-tree-buffer nil)
 '(ecb-windows-height 0.2)
 '(ecb-windows-width 0.17)
 '(ensime-auto-connect (quote ask))
 '(ensime-graphical-tooltips t)
 '(global-hl-line-mode t)
 '(highlight-80+-columns 100)
 '(magit-process-popup-time 30)
 '(magit-repo-dirs (quote ("~/ps/" "~/workspace/")))
 '(save-place t nil (saveplace))
 '(scala-mode-feature:electric-on-per-default nil)
 '(show-paren-mode t)
 '(standard-indent 2)
 '(tab-always-indent (quote complete))
 '(tool-bar-mode nil)
 '(transient-mark-mode nil)
 '(vimpulse-fold-level 3)
 '(viper-ESC-moves-cursor-back t)
 '(viper-auto-indent t)
 '(viper-ex-style-editing nil)
 '(viper-insert-state-cursor-color nil)
 '(viper-parse-sexp-ignore-comments nil)
 '(viper-shift-width 2)
 '(viper-syntax-preference (quote extended))
 '(viper-want-ctl-h-help t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(elscreen-tab-background-face ((((class color)) (:background "#282828"))))
 '(elscreen-tab-control-face ((((class color)) (:background "#1f1f1f" :foreground "white"))))
 '(elscreen-tab-current-screen-face ((((class color)) (:background "#1f1f1f" :foreground "white"))))
 '(elscreen-tab-other-screen-face ((((class color)) (:background "#3D3D3D" :foreground "white"))))
 '(show-paren-mismatch ((t (:background "red" :foreground "white")))))
